version: '3'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: gpmarchi/nodetest
    container_name: fullcycle_docker_node
    networks:
      - mynet
    entrypoint: dockerize -wait tcp://fullcycle_docker_mysql:3306 -timeout 20s docker-entrypoint.sh node ./index.js
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    tty: true
    image: gpmarchi/nginx
    container_name: fullcycle_docker_nginx
    ports:
      - "8080:80"
    networks:
      - mynet

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: fullcycle_docker_mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
